# Generated by Django 4.2.7 on 2025-06-22 20:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_productor_p', models.CharField(help_text='Cédula del productor', max_length=10)),
                ('nombre_finca_p', models.CharField(help_text='Nombre de la finca', max_length=100)),
                ('id_parcela', models.CharField(help_text='Identificador único de la parcela', max_length=20)),
                ('superficie', models.FloatField(help_text='Superficie de la parcela en hectáreas', validators=[django.core.validators.MinValueValidator(0, 'La superficie debe ser mayor a 0'), django.core.validators.MaxValueValidator(10000, 'La superficie no puede ser mayor a 10,000')])),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'db_table': 'parcelas',
                'ordering': ['id_productor_p', 'nombre_finca_p', 'id_parcela'],
                'unique_together': {('id_productor_p', 'nombre_finca_p', 'id_parcela')},
            },
        ),
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_productor', models.CharField(help_text='Cédula del productor', max_length=10)),
                ('nombre_finca', models.CharField(help_text='Nombre de la finca', max_length=100)),
                ('ubicacion', models.CharField(help_text='Ubicación de la finca', max_length=200)),
                ('tipo_de_suelo', models.CharField(help_text='Tipo de suelo de la finca', max_length=50)),
                ('fecha_registro_finca', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro de la finca')),
            ],
            options={
                'verbose_name': 'Finca',
                'verbose_name_plural': 'Fincas',
                'db_table': 'fincas',
                'ordering': ['id_productor', 'nombre_finca'],
                'unique_together': {('id_productor', 'nombre_finca')},
            },
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cultivo', models.CharField(help_text='Tipo de cultivo', max_length=50)),
                ('area_cultivo', models.FloatField(help_text='Área de cultivo en hectáreas', validators=[django.core.validators.MinValueValidator(0.01, 'El área debe ser mayor a 0.01'), django.core.validators.MaxValueValidator(10000, 'El área no puede ser mayor a 10,000')])),
                ('fecha_siembra', models.DateField(help_text='Fecha de siembra')),
                ('fecha_cosecha', models.DateField(help_text='Fecha de cosecha')),
                ('estado_cultivo', models.CharField(help_text='Estado actual del cultivo', max_length=20)),
                ('id_finca', models.ForeignKey(help_text='Finca donde se cultiva', on_delete=django.db.models.deletion.CASCADE, to='terrenos_app.finca')),
            ],
            options={
                'verbose_name': 'Cultivo',
                'verbose_name_plural': 'Cultivos',
                'db_table': 'cultivos',
                'ordering': ['id_finca', 'tipo_cultivo'],
            },
        ),
    ]
