# Generated by Django 4.2.7 on 2025-06-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_cedula', models.CharField(help_text='Cédula del usuario receptor', max_length=10)),
                ('mensaje', models.TextField(help_text='Mensaje de la notificación')),
                ('tipo', models.CharField(help_text='Tipo de notificación', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
