# Generated by Django 4.2.7 on 2025-06-22 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id_maquinaria', models.CharField(help_text='Identificador único de la maquinaria', max_length=20, primary_key=True, serialize=False)),
                ('propietario_m', models.CharField(help_text='Cédula del propietario', max_length=10)),
                ('tipo', models.CharField(help_text='Tipo de maquinaria', max_length=50)),
                ('marca', models.CharField(help_text='Marca de la maquinaria', max_length=50)),
                ('modelo', models.CharField(help_text='Modelo de la maquinaria', max_length=50)),
                ('año', models.IntegerField(help_text='Año de fabricación', validators=[django.core.validators.MinValueValidator(1900, 'El año debe ser mayor o igual a 1900'), django.core.validators.MaxValueValidator(2100, 'El año no puede ser mayor a 2100')])),
            ],
            options={
                'verbose_name': 'Maquinaria',
                'verbose_name_plural': 'Maquinaria',
                'db_table': 'maquinaria',
                'ordering': ['propietario_m', 'tipo', 'marca'],
            },
        ),
        migrations.CreateModel(
            name='ReservaMaquinaria',
            fields=[
                ('id_listado_r', models.CharField(help_text='Identificador único del listado de reserva', max_length=20, primary_key=True, serialize=False)),
                ('id_maquinaria', models.CharField(help_text='ID de la maquinaria', max_length=20)),
                ('propietario_r', models.CharField(help_text='Cédula del propietario', max_length=10)),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio de la reserva')),
                ('fecha_fin', models.DateField(help_text='Fecha de fin de la reserva')),
            ],
            options={
                'verbose_name': 'Reserva de Maquinaria',
                'verbose_name_plural': 'Reservas de Maquinaria',
                'db_table': 'reserva_maquinaria',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='VentaMaquinaria',
            fields=[
                ('id_listado_v', models.CharField(help_text='Identificador único del listado de venta', max_length=20, primary_key=True, serialize=False)),
                ('id_maquinaria', models.CharField(help_text='ID de la maquinaria', max_length=20)),
                ('propietario_v', models.CharField(help_text='Cédula del propietario', max_length=10)),
                ('fecha_v', models.DateField(help_text='Fecha de publicación de la venta')),
                ('precio', models.FloatField(help_text='Precio de venta', validators=[django.core.validators.MinValueValidator(0, 'El precio debe ser mayor o igual a 0'), django.core.validators.MaxValueValidator(1000000, 'El precio no puede ser mayor a 1,000,000')])),
            ],
            options={
                'verbose_name': 'Venta de Maquinaria',
                'verbose_name_plural': 'Ventas de Maquinaria',
                'db_table': 'venta_maquinaria',
                'ordering': ['-fecha_v'],
            },
        ),
    ]
