server {
    listen 80;

    location /usuarios/ {
        proxy_pass http://usuarios:8000/;
    }

    location /terrenos/ {
        proxy_pass http://terrenos:8001/;
    }

    location /maquinaria/ {
        proxy_pass http://maquinaria:8002/;
    }

    location /notificaciones/ {
        proxy_pass http://notificaciones:8003/;
    }
}

